name: mlp_depth
disp_name: mlp_prosthesis_test
dir: /home/woody/iwnt/iwnt164h/mlp_dataset/prospthesisproject-Data/Code/Data
filenames: /home/woody/iwnt/iwnt164h/mlp_dataset/prospthesisproject-Data/Code/Data/mlp_prosthesis_test_files.txt
eigen_valid_mask: true