name: nyu_depth
disp_name: nyu_depth_test_full
dir: /home/woody/iwnt/iwnt164h/nyu_testset #nyuv2/nyu_labeled_extracted.tar
filenames: Marigold/data_split/nyu_depth/labeled/filename_list_test.txt #data_split/nyu_depth/labeled/filename_list_test.txt
eigen_valid_mask: true
